// Variables that will be generated
var theme = [
'Space',
'Pirate',
'Ancient Greek',
'French',
'Prehistoric',
'Athletic',
'Olympic',
'Nerdy',
'Rock n roll',
'Punk',
'Reggae',
'Pop-star',
'Mod',
'Hippie',
'Raver',
'Goth',
'Leather daddy',
'Plastic',
'Grunge',
'Art deco',
'Art nouveau',
'Renaissance',
'Flamenco',
'Carnivale',
'Halloween',
'Christmas',
'Dead',
'Ghost',
'Baby',
'Serial killer',
'Insectoid',
'Sexy',
'Monochromatic',
'Evil twin',
'Luxury',
'Bohemian',
'Mutant',
'Hunchback',
'Occult',
'Robot',
'Tiny',
'Giant',
'Winter',
'Summer holiday',
'Cyberpunk',
'Steampunk',
'Ancient Egyptian',
'Budget',
'Doomsday prepper',
'Elderly',
'Tropicana',
'Aquatic',
'Western',
'Warrior',
'Post-apocalypse'
]

var style = [
'wizard',
'pirate',
'mime',
'mascot',
'bride',
'groom',
'royal guard',
'policeperson',
'fireperson',
'doctor',
'stripper',
'construction worker',
'cowpoke',
'pilot',
'clown',
'scientist',
'milkman',
'farmer',
'postal worker',
'astronaut',
'gymnast',
'politician',
'servant',
'king',
'queen',
'wait staff',
'lifeguard',
'bounty hunter',
'fisherman',
'superhero',
'lizard-person',
'illuminati',
'priest',
'nun',
'shaman',
'psychic',
'pickpocket',
'thief',
'criminal',
'door-to-door salesman',
'chimneysweep',
'baker',
'cleaner',
'lawyer',
'artist',
'witch',
'robot',
'soldier',
'prospector',
'miner',
'scavenger',
'air hostess',
'tour guide',
'hipster',
'hermit',
'musician',
'busker',
'dad',
'mum',
'tourist',
'drug dealer',
'student',
'angel',
'demon',
'cult leader',
'dj',
'bird watcher',
'hunter',
'crafter',
'samurai',
]

// Converts the two variables into a string
function newIdea() {
	var randomNum1 = Math.floor(Math.random() * (theme.length));
	var randomNum2 = Math.floor(Math.random() * (style.length));
	document.getElementById('ideaDisplay').innerHTML = theme[randomNum1] + ' ' + style[randomNum2];
}

// Randomises background colour
function randomBg() {
	var x = Math.floor(Math.random() * 256);
	var y = Math.floor(Math.random() * 256);
	var z = Math.floor(Math.random() * 256);
	var bgColor = "rgb(" + x + "," + y + ',' + z + ")";
console.log(bgColor);
	
	document.body.style.background = bgColor;
}

randomBg();